### ISSUE TITLE
关于同文件夹下有数十个文件时，只上传成功部分

### ISSUE THREAD

**Issue by robinma** [hoyangtsai/gulp-file-post#1]
我这里有个static文件夹，里面有一百多个文件，当我配置上传时，可能只上传成功十几个。

```
gulp.task('asyncFiles', () => {
    gulp.src(['./dist/**/*.*'])
         .pipe(filePost(staticConfig));
});

```

**Comment by hoyangtsai** [comment]
@robinma 
我先用`tree ./local/page`指令驗證一下文件的數量 (page文件夾底下包含多層子文件夾)

<img width="437" alt="gulp-test-3" src="https://user-images.githubusercontent.com/1687532/28056091-3250d4e2-664e-11e7-9ab2-cef1e8504067.png">

然後再寫一個 gulp 測試 demo
```js
var gulp = require('gulp');
var upload = require('gulp-file-post');

gulp.task('default', function() {
  return gulp.src('./local/page/**/*.*')
    .pipe(upload({
      url: 'http://example.com/receiver.php',
      root: 'local',
      remotePath: '/path/file/goes/gulp-test'
    })
  );
});
```
<img width="611" alt="gulp-test-5" src="https://user-images.githubusercontent.com/1687532/28056158-7013983c-664e-11e7-9d19-a5211c64c603.png">

執行結果和 tree 的文件數量一樣

所以不是 plugin 的問題，確認一下其他問題吧
